
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mysalecity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class agent
{

    public long id { get; set; }

    public long user_id { get; set; }

    public long company_id { get; set; }

    public long agent_status { get; set; }

    public System.DateTime date_create { get; set; }



    public virtual agent_status agent_status1 { get; set; }

    public virtual company company { get; set; }

    public virtual user user { get; set; }

}

}
