
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mysalecity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class company
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public company()
    {

        this.agents = new HashSet<agent>();

        this.tasks = new HashSet<task>();

        this.tickets = new HashSet<ticket>();

    }


    public long id { get; set; }

    public string company_name { get; set; }

    public long city { get; set; }

    public string adress { get; set; }

    public string web_adress { get; set; }

    public string company_login { get; set; }

    public string company_password { get; set; }

    public string inn { get; set; }

    public int personal_account { get; set; }

    public System.DateTime registration_date { get; set; }

    public int paying_time { get; set; }

    public long company_status { get; set; }

    public long category { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<agent> agents { get; set; }

    public virtual category category1 { get; set; }

    public virtual city city1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<task> tasks { get; set; }

    public virtual company_status company_status1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ticket> tickets { get; set; }

}

}
