

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mysalecity.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class mysale_dbEntities : DbContext
{
    public mysale_dbEntities()
        : base("name=mysale_dbEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<agent_status> agent_status { get; set; }

    public virtual DbSet<agent> agents { get; set; }

    public virtual DbSet<category> categories { get; set; }

    public virtual DbSet<city> cities { get; set; }

    public virtual DbSet<company> companies { get; set; }

    public virtual DbSet<company_status> company_status { get; set; }

    public virtual DbSet<task> tasks { get; set; }

    public virtual DbSet<ticket> tickets { get; set; }

    public virtual DbSet<tickets_type> tickets_type { get; set; }

    public virtual DbSet<user_statuses> user_statuses { get; set; }

    public virtual DbSet<user> users { get; set; }

    public virtual DbSet<tasks_view> tasks_view { get; set; }

}

}

