
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mysalecity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class task
{

    public long id { get; set; }

    public long company_id { get; set; }

    public System.DateTime date_start { get; set; }

    public System.DateTime date_finish { get; set; }

    public string title { get; set; }

    public string text { get; set; }

    public string info { get; set; }



    public virtual company company { get; set; }

}

}
