
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mysalecity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ticket
{

    public long id { get; set; }

    public long ticket_type { get; set; }

    public long from { get; set; }

    public long @for { get; set; }

    public string text { get; set; }



    public virtual company company { get; set; }

    public virtual user user { get; set; }

    public virtual tickets_type tickets_type { get; set; }

}

}
