
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mysalecity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class user
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public user()
    {

        this.agents = new HashSet<agent>();

        this.tickets = new HashSet<ticket>();

    }


    public long id { get; set; }

    public System.DateTime registration_date { get; set; }

    public long user_status { get; set; }

    public string name { get; set; }

    public string surname { get; set; }

    public string middle_name { get; set; }

    public System.DateTime date_birth { get; set; }

    public string tel_number { get; set; }

    public string login { get; set; }

    public string password { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<agent> agents { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ticket> tickets { get; set; }

    public virtual user_statuses user_statuses { get; set; }

}

}
